export const environment = {
    API_BASE_URL: "http://localhost:3000/api/",
    API_URL_USERS: "http://localhost:3000/api/users",
    API_URL_USERS_LOGIN: "http://localhost:3000/api/users/login",
    API_URL_SONGS: "http://localhost:3000/api/songs",
    API_URL_SONGS_SLASH: "http://localhost:3000/api/songs/",
    API_URL_SLASH_ARTISTS: "/artists",
    API_URL_SLASH_ARTISTS_SLASH: "/artists/",

    DEFAULT_PAGE_ARRAY: [5, 10, 20, 25, 50],
    DEFAULT_EMPTY_ARRAY: [],
    DEFAULT_TRUE: true,
    DEFAULT_FALSE: false,
    DEFAULT_TIME_OUT: 500,
    EMPTY_STRING: "",
    ZERO: 0,
    DEFAULT_SORT_VALUE: 1,

    SONGS: "songs",
    SONGS_SLASH: "songs/",
    SONGS_ADDSONG: "songs/addsong",
    SONGS_SONGID_EDIT: "songs/:songId/edit",
    SONGS_SONGID: "songs/:songId",
    REGISTER: "register",
    LOGIN: "login",
    SEARCH: "search",
    PROFILE: "profile",
    SONGS_SONGID_ADDARTIST: "songs/:songId/addArtist",
    SONGS_SONGID_ARTISTS_ARTISTID_EDIT: "songs/:songId/artists/:artistId/edit",
    ERROR_STAR: "**",

    TOKEN: "token",
    BEARER_SPACE: "Bearer ",
    COLLON: ":",
    ZERO_STRING: "0",
    SONGID: "songId",
    NAME: "name",
    PASSWORD: "password",
    USER_NAME: "username",
    TITLE: "title",
    DURATION: "duration",
    ARTISTS: "artists",
    AGE: "age",
    ARTISTID: "artistId",

    APPLICATION_TITLE: "MEAN Music",
    SORT: "Sort",
    UN_SORT: "Unsort",
    ADD_SONG: "Add Song",
    UPDATE_SONG: "Update Song",
    ADD_ARTIST: "Add Artist",
    UPDATE_ARTIST: "Update Artist",

    MSG_USER_REGISTRATION_SUCCESSFULLY: "User registration successfully",
    MSG_FAILED_TO_REGISTER_USER: "Failed to register user: All fields are required and the Password must match Repeat Password",
    MSG_FAILED_TO_LOGIN: "Failed to login: All fields are required",
    MSG_DO_YOU_WANT_TO_DELETE_SPACE: "Do you want to delete ",
    MSG_DELETE_SUCCESSFULLY: "Delete successfully!",
    MSG_YOUR_SONG_HAS_BEEN_UPDATED: "Your song has been updated",
    MSG_YOUR_SONG_HAS_BEEN_CREATED: "Your song has been created",
    MSG_YOUR_ARTIST_HAS_BEEN_CREATED: "Your artist has been created",
    MSG_YOUR_ARTIST_HAS_BEEN_UPDATED: "Your artist has been updated",
    MSG_FAILED_TO_ADD_SONG: "Failed to add song: All fields are required and the Duration should be number with condition (1 <= duration <= 800)",
    MSG_FAILED_TO_UPDATE_SONG: "Failed to update song: All fields are required and the Duration should be number with condition (1 <= duration <= 800)",
    MSG_FAILED_TO_ADD_ARTIST: "Failed to add artist: All fields are required and the Age should be number with condition (6 <= age <= 99)",
    MSG_FAILED_TO_UPDATE_ARTIST: "Failed to update artist: All fields are required and the Age should be number with condition (6 <= age <= 99)"
};
